version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: forex-php:latest
    container_name: forex_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PHP_MEMORY_LIMIT: 512M
    networks: [forexnet]
    depends_on:
      - mysql

  nginx:
    image: nginx:1.25-alpine
    container_name: forex_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [forexnet]
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: forex_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks: [forexnet]

volumes:
  dbdata:

networks:
  forexnet:
    driver: bridge
